Added options for command line output.

diff --git a/remove-image-border b/remove-image-border
--- a/remove-image-border
+++ b/remove-image-border
@@ -1,15 +1,42 @@
 #!/bin/bash -
 
+scriptname=$(basename -- "$0")
 if [ $# -eq 0 ]; then
-  echo >&2 "Usage: $(basename $0) file ..."
+  echo >&2 "Usage: ${scriptname} file ..."
   exit 1
 fi
 
-tmpdir=$(mktemp -d)
+tmpdir=$(mktemp -d "${scriptname}-XXXXXX.tmp")
+trap "rm -rf $tmpdir" EXIT
+
+OPTSTRING=':fs'
+print_file_name=0
+print_script_name=0
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    f)
+      print_file_name=1
+      ;;
+    s)
+      print_script_name=1  # implies print_file_name
+      ;;
+    ?)
+      echo >&2 "Invalid option: -${OPTARG}."
+      exit 1
+      ;;
+  esac
+done
+shift $((OPTIND-1))
+
 for file; do
-  echo "$file"
+  if (( print_script_name )); then
+    printf '%s: %s\n' "$(basename -- "$0")" "$file"
+  elif (( print_file_name )); then
+    printf '%s\n' "$file"
+  fi
   base=$(basename "$file")
   tmpfile="$tmpdir/$base"
-  convert -fuzz 20% -trim "$file" "$tmpfile" && touch -r "$file" "$tmpfile" && mv "$tmpfile" "$file"
+  convert -fuzz 20% -trim "$file" "$tmpfile" &&
+    touch -r "$file" "$tmpfile" &&
+    mv "$tmpfile" "$file"
 done
-rmdir "$tmpdir"
